apiVersion: batch/v1
kind: Job
metadata:
  name: spark-batch-submit
spec:
  template:
    metadata:
      labels:
        app: spark-batch-submit
    spec:
      restartPolicy: Never
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "512Mi"
        - name: temp-data
          emptyDir: {}
      containers:
      - name: spark-submit
        image: quaqducc/spark-batch-computing:v1
        imagePullPolicy: IfNotPresent
        env:
          - name: SPARK_DRIVER_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_BROKER
            value: "my-kafka:9092"
          - name: TOPIC_NAME
            value: "traffic_data"
          - name: MINIO_ENDPOINT
            value: "my-minio:9000"
          - name: MINIO_ACCESS_KEY
            value: "bigdataproject"
          - name: MINIO_SECRET_KEY
            value: "bigdataproject"
          - name: MINIO_BUCKET
            value: "configs"
          - name: SPARK_MASTER
            value: "spark://spark-master:7077"
          - name: SPARK_APP_NAME
            value: "YOLO_Inference_Job"
          - name: IMG_SIZE
            value: "320"
          - name: MONGO_URI
            value: "mongodb://root:bigdataproject@my-mongodb.default.svc.cluster.local:27017/traffic_db?authSource=admin"
          - name: DB_NAME
            value: "traffic_db"
        command: ["/opt/spark/bin/spark-submit"]
        args:
          - "--master"
          - "spark://spark-master:7077"
          - "--deploy-mode"
          - "client"
          - "--conf"
          - "spark.driver.bindAddress=0.0.0.0"
          - "--conf"
          - "spark.driver.host=$(SPARK_DRIVER_POD_IP)"
          - "--conf"
          - "spark.driver.port=33043"
          - "--conf"
          - "spark.blockManager.port=33044"
          - "--packages"
          - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1,org.mongodb.spark:mongo-spark-connector_2.12:10.2.1"
          - "--conf"
          - "spark.executorEnv.MINIO_ENDPOINT=my-minio:9000"
          - "--conf"
          - "spark.executorEnv.MINIO_ACCESS_KEY=bigdataproject"
          - "--conf"
          - "spark.executorEnv.MINIO_SECRET_KEY=bigdataproject"
          - "--conf"
          - "spark.executorEnv.MINIO_BUCKET=configs"
          - "--conf"
          - "spark.executorEnv.IMG_SIZE=320"
          - "--conf"
          - "spark.executor.instances=1"
          - "--conf"
          - "spark.executor.memory=512m"
          - "--conf"
          - "spark.executor.memoryOverhead=256m"
          - "--conf"
          - "spark.executor.cores=1"
          - "--conf"
          - "spark.driver.memory=1g"
          - "--py-files"
          - "/app/util.py"
          - "/app/main.py"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /tmp
            name: temp-data

